### ISSUE TITLE
java版本初始化报错

### ISSUE THREAD

**Issue by memory8464** [YoTest-team/YoTest-Android-SDK#1]
YoTestCaptcha.init(this, "ID");
Non-static method 'init(android.content.Context, java.lang.String, kotlin.jvm.functions.Function2<? super java.lang.Integer,? super java.lang.String,kotlin.Unit>)' cannot be referenced from a static context

**Comment by ErosZy** [comment]
please update to 1.0.3, thx.

**Comment by memory8464** [comment]
感谢你的帮助。
